; Generated by Enhanced C Compiler
; Support for arrays, structs, malloc, and JVM features
.org 0x8000

; Initialize stack pointer
LOADI R30, #0x000F0000
; Initialize heap pointer
LOADI R29, #0x20000

; Function: main
main:
LOADI R1, #131072
MOVE R2, R0
LOADI R3, #42
MOVE R2, R3
MOVE R1, R2
HALT
HALT


HALT
