; Generated by Simple C Compiler
; Custom RISC Assembly Output

    ; Runtime support functions
malloc:
    ; Simple malloc - returns fixed heap addresses
    load r1, heap_ptr
    add r2, r1, r0
    store r2, heap_ptr
    mov r0, r1
    ret

putchar:
    ; Output character in r0
    out r0
    ret

strlen:
    ; String length - string pointer in r0
    mov r1, r0
    mov r0, #0
strlen_loop:
    load r2, [r1]
    cmp r2, #0
    je strlen_end
    add r0, r0, #1
    add r1, r1, #1
    jmp strlen_loop
strlen_end:
    ret

; Data section
heap_ptr: .word 0x10000

    ; Compound statement
    ; Function declaration
log_very_simple_string_d_f474b09e:
    push fp
    mov fp, sp
    sub sp, sp, #64
    ; Compound statement
    ; Variable declaration
; Variable char1 allocated at [fp-4]
    mov r1, #86
    ; Store initializer value for char1
    store r1, [fp-4]
    ; Variable declaration
; Variable char2 allocated at [fp-8]
    mov r1, #101
    ; Store initializer value for char2
    store r1, [fp-8]
    ; Variable declaration
; Variable char3 allocated at [fp-12]
    mov r1, #114
    ; Store initializer value for char3
    store r1, [fp-12]
    ; Variable declaration
; Variable char4 allocated at [fp-16]
    mov r1, #121
    ; Store initializer value for char4
    store r1, [fp-16]
    ; Variable declaration
; Variable char5 allocated at [fp-20]
    mov r1, #32
    ; Store initializer value for char5
    store r1, [fp-20]
    ; Variable declaration
; Variable char6 allocated at [fp-24]
    mov r1, #83
    ; Store initializer value for char6
    store r1, [fp-24]
    ; Variable declaration
; Variable char7 allocated at [fp-28]
    mov r1, #105
    ; Store initializer value for char7
    store r1, [fp-28]
    ; Variable declaration
; Variable char8 allocated at [fp-32]
    mov r1, #109
    ; Store initializer value for char8
    store r1, [fp-32]
    ; Variable declaration
; Variable char9 allocated at [fp-36]
    mov r1, #112
    ; Store initializer value for char9
    store r1, [fp-36]
    ; Variable declaration
; Variable char10 allocated at [fp-40]
    mov r1, #108
    ; Store initializer value for char10
    store r1, [fp-40]
    ; Variable declaration
; Variable char11 allocated at [fp-44]
    mov r1, #101
    ; Store initializer value for char11
    store r1, [fp-44]
    ; Variable declaration
; Variable char12 allocated at [fp-48]
    mov r1, #32
    ; Store initializer value for char12
    store r1, [fp-48]
    ; Variable declaration
; Variable char13 allocated at [fp-52]
    mov r1, #83
    ; Store initializer value for char13
    store r1, [fp-52]
    ; Variable declaration
; Variable char14 allocated at [fp-56]
    mov r1, #116
    ; Store initializer value for char14
    store r1, [fp-56]
    ; Variable declaration
; Variable char15 allocated at [fp-60]
    mov r1, #114
    ; Store initializer value for char15
    store r1, [fp-60]
    ; Variable declaration
; Variable char16 allocated at [fp-64]
    mov r1, #105
    ; Store initializer value for char16
    store r1, [fp-64]
    ; Variable declaration
; Variable char17 allocated at [fp-68]
    mov r1, #110
    ; Store initializer value for char17
    store r1, [fp-68]
    ; Variable declaration
; Variable char18 allocated at [fp-72]
    mov r1, #103
    ; Store initializer value for char18
    store r1, [fp-72]
    ; Variable declaration
; Variable char19 allocated at [fp-76]
    mov r1, #32
    ; Store initializer value for char19
    store r1, [fp-76]
    ; Variable declaration
; Variable char20 allocated at [fp-80]
    mov r1, #68
    ; Store initializer value for char20
    store r1, [fp-80]
    ; Variable declaration
; Variable char21 allocated at [fp-84]
    mov r1, #101
    ; Store initializer value for char21
    store r1, [fp-84]
    ; Variable declaration
; Variable char22 allocated at [fp-88]
    mov r1, #109
    ; Store initializer value for char22
    store r1, [fp-88]
    ; Variable declaration
; Variable char23 allocated at [fp-92]
    mov r1, #111
    ; Store initializer value for char23
    store r1, [fp-92]
    ; Variable declaration
; Variable char24 allocated at [fp-96]
    mov r1, #10
    ; Store initializer value for char24
    store r1, [fp-96]
    ; Return statement
    mov r0, #0
    add sp, sp, #64
    pop fp
    ret 
log_very_simple_string_d_f474b09e_end:
    add sp, sp, #64
    pop fp
    ret 

    ; Function declaration
log_value_of_x_10_n_c529459d:
    push fp
    mov fp, sp
    sub sp, sp, #64
    ; Compound statement
    ; Variable declaration
; Variable char1 allocated at [fp-4]
    mov r1, #86
    ; Store initializer value for char1
    store r1, [fp-4]
    ; Variable declaration
; Variable char2 allocated at [fp-8]
    mov r1, #97
    ; Store initializer value for char2
    store r1, [fp-8]
    ; Variable declaration
; Variable char3 allocated at [fp-12]
    mov r1, #108
    ; Store initializer value for char3
    store r1, [fp-12]
    ; Variable declaration
; Variable char4 allocated at [fp-16]
    mov r1, #117
    ; Store initializer value for char4
    store r1, [fp-16]
    ; Variable declaration
; Variable char5 allocated at [fp-20]
    mov r1, #101
    ; Store initializer value for char5
    store r1, [fp-20]
    ; Variable declaration
; Variable char6 allocated at [fp-24]
    mov r1, #32
    ; Store initializer value for char6
    store r1, [fp-24]
    ; Variable declaration
; Variable char7 allocated at [fp-28]
    mov r1, #111
    ; Store initializer value for char7
    store r1, [fp-28]
    ; Variable declaration
; Variable char8 allocated at [fp-32]
    mov r1, #102
    ; Store initializer value for char8
    store r1, [fp-32]
    ; Variable declaration
; Variable char9 allocated at [fp-36]
    mov r1, #32
    ; Store initializer value for char9
    store r1, [fp-36]
    ; Variable declaration
; Variable char10 allocated at [fp-40]
    mov r1, #88
    ; Store initializer value for char10
    store r1, [fp-40]
    ; Variable declaration
; Variable char11 allocated at [fp-44]
    mov r1, #61
    ; Store initializer value for char11
    store r1, [fp-44]
    ; Variable declaration
; Variable char12 allocated at [fp-48]
    mov r1, #49
    ; Store initializer value for char12
    store r1, [fp-48]
    ; Variable declaration
; Variable char13 allocated at [fp-52]
    mov r1, #48
    ; Store initializer value for char13
    store r1, [fp-52]
    ; Variable declaration
; Variable char14 allocated at [fp-56]
    mov r1, #10
    ; Store initializer value for char14
    store r1, [fp-56]
    ; Return statement
    mov r0, #0
    add sp, sp, #64
    pop fp
    ret 
log_value_of_x_10_n_c529459d_end:
    add sp, sp, #64
    pop fp
    ret 

    ; Function declaration
log_value_of_y_20_n_b62ac48a:
    push fp
    mov fp, sp
    sub sp, sp, #64
    ; Compound statement
    ; Variable declaration
; Variable char1 allocated at [fp-4]
    mov r1, #86
    ; Store initializer value for char1
    store r1, [fp-4]
    ; Variable declaration
; Variable char2 allocated at [fp-8]
    mov r1, #97
    ; Store initializer value for char2
    store r1, [fp-8]
    ; Variable declaration
; Variable char3 allocated at [fp-12]
    mov r1, #108
    ; Store initializer value for char3
    store r1, [fp-12]
    ; Variable declaration
; Variable char4 allocated at [fp-16]
    mov r1, #117
    ; Store initializer value for char4
    store r1, [fp-16]
    ; Variable declaration
; Variable char5 allocated at [fp-20]
    mov r1, #101
    ; Store initializer value for char5
    store r1, [fp-20]
    ; Variable declaration
; Variable char6 allocated at [fp-24]
    mov r1, #32
    ; Store initializer value for char6
    store r1, [fp-24]
    ; Variable declaration
; Variable char7 allocated at [fp-28]
    mov r1, #111
    ; Store initializer value for char7
    store r1, [fp-28]
    ; Variable declaration
; Variable char8 allocated at [fp-32]
    mov r1, #102
    ; Store initializer value for char8
    store r1, [fp-32]
    ; Variable declaration
; Variable char9 allocated at [fp-36]
    mov r1, #32
    ; Store initializer value for char9
    store r1, [fp-36]
    ; Variable declaration
; Variable char10 allocated at [fp-40]
    mov r1, #89
    ; Store initializer value for char10
    store r1, [fp-40]
    ; Variable declaration
; Variable char11 allocated at [fp-44]
    mov r1, #61
    ; Store initializer value for char11
    store r1, [fp-44]
    ; Variable declaration
; Variable char12 allocated at [fp-48]
    mov r1, #50
    ; Store initializer value for char12
    store r1, [fp-48]
    ; Variable declaration
; Variable char13 allocated at [fp-52]
    mov r1, #48
    ; Store initializer value for char13
    store r1, [fp-52]
    ; Variable declaration
; Variable char14 allocated at [fp-56]
    mov r1, #10
    ; Store initializer value for char14
    store r1, [fp-56]
    ; Return statement
    mov r0, #0
    add sp, sp, #64
    pop fp
    ret 
log_value_of_y_20_n_b62ac48a_end:
    add sp, sp, #64
    pop fp
    ret 

    ; Function declaration
log_value_of_sum_30_n_0b323078:
    push fp
    mov fp, sp
    sub sp, sp, #64
    ; Compound statement
    ; Variable declaration
; Variable char1 allocated at [fp-4]
    mov r1, #86
    ; Store initializer value for char1
    store r1, [fp-4]
    ; Variable declaration
; Variable char2 allocated at [fp-8]
    mov r1, #97
    ; Store initializer value for char2
    store r1, [fp-8]
    ; Variable declaration
; Variable char3 allocated at [fp-12]
    mov r1, #108
    ; Store initializer value for char3
    store r1, [fp-12]
    ; Variable declaration
; Variable char4 allocated at [fp-16]
    mov r1, #117
    ; Store initializer value for char4
    store r1, [fp-16]
    ; Variable declaration
; Variable char5 allocated at [fp-20]
    mov r1, #101
    ; Store initializer value for char5
    store r1, [fp-20]
    ; Variable declaration
; Variable char6 allocated at [fp-24]
    mov r1, #32
    ; Store initializer value for char6
    store r1, [fp-24]
    ; Variable declaration
; Variable char7 allocated at [fp-28]
    mov r1, #111
    ; Store initializer value for char7
    store r1, [fp-28]
    ; Variable declaration
; Variable char8 allocated at [fp-32]
    mov r1, #102
    ; Store initializer value for char8
    store r1, [fp-32]
    ; Variable declaration
; Variable char9 allocated at [fp-36]
    mov r1, #32
    ; Store initializer value for char9
    store r1, [fp-36]
    ; Variable declaration
; Variable char10 allocated at [fp-40]
    mov r1, #83
    ; Store initializer value for char10
    store r1, [fp-40]
    ; Variable declaration
; Variable char11 allocated at [fp-44]
    mov r1, #117
    ; Store initializer value for char11
    store r1, [fp-44]
    ; Variable declaration
; Variable char12 allocated at [fp-48]
    mov r1, #109
    ; Store initializer value for char12
    store r1, [fp-48]
    ; Variable declaration
; Variable char13 allocated at [fp-52]
    mov r1, #61
    ; Store initializer value for char13
    store r1, [fp-52]
    ; Variable declaration
; Variable char14 allocated at [fp-56]
    mov r1, #51
    ; Store initializer value for char14
    store r1, [fp-56]
    ; Variable declaration
; Variable char15 allocated at [fp-60]
    mov r1, #48
    ; Store initializer value for char15
    store r1, [fp-60]
    ; Variable declaration
; Variable char16 allocated at [fp-64]
    mov r1, #10
    ; Store initializer value for char16
    store r1, [fp-64]
    ; Return statement
    mov r0, #0
    add sp, sp, #64
    pop fp
    ret 
log_value_of_sum_30_n_0b323078_end:
    add sp, sp, #64
    pop fp
    ret 

    ; Function declaration
log_sum_check_passed_n_6f9303c9:
    push fp
    mov fp, sp
    sub sp, sp, #64
    ; Compound statement
    ; Variable declaration
; Variable char1 allocated at [fp-4]
    mov r1, #83
    ; Store initializer value for char1
    store r1, [fp-4]
    ; Variable declaration
; Variable char2 allocated at [fp-8]
    mov r1, #117
    ; Store initializer value for char2
    store r1, [fp-8]
    ; Variable declaration
; Variable char3 allocated at [fp-12]
    mov r1, #109
    ; Store initializer value for char3
    store r1, [fp-12]
    ; Variable declaration
; Variable char4 allocated at [fp-16]
    mov r1, #32
    ; Store initializer value for char4
    store r1, [fp-16]
    ; Variable declaration
; Variable char5 allocated at [fp-20]
    mov r1, #99
    ; Store initializer value for char5
    store r1, [fp-20]
    ; Variable declaration
; Variable char6 allocated at [fp-24]
    mov r1, #104
    ; Store initializer value for char6
    store r1, [fp-24]
    ; Variable declaration
; Variable char7 allocated at [fp-28]
    mov r1, #101
    ; Store initializer value for char7
    store r1, [fp-28]
    ; Variable declaration
; Variable char8 allocated at [fp-32]
    mov r1, #99
    ; Store initializer value for char8
    store r1, [fp-32]
    ; Variable declaration
; Variable char9 allocated at [fp-36]
    mov r1, #107
    ; Store initializer value for char9
    store r1, [fp-36]
    ; Variable declaration
; Variable char10 allocated at [fp-40]
    mov r1, #32
    ; Store initializer value for char10
    store r1, [fp-40]
    ; Variable declaration
; Variable char11 allocated at [fp-44]
    mov r1, #112
    ; Store initializer value for char11
    store r1, [fp-44]
    ; Variable declaration
; Variable char12 allocated at [fp-48]
    mov r1, #97
    ; Store initializer value for char12
    store r1, [fp-48]
    ; Variable declaration
; Variable char13 allocated at [fp-52]
    mov r1, #115
    ; Store initializer value for char13
    store r1, [fp-52]
    ; Variable declaration
; Variable char14 allocated at [fp-56]
    mov r1, #115
    ; Store initializer value for char14
    store r1, [fp-56]
    ; Variable declaration
; Variable char15 allocated at [fp-60]
    mov r1, #101
    ; Store initializer value for char15
    store r1, [fp-60]
    ; Variable declaration
; Variable char16 allocated at [fp-64]
    mov r1, #100
    ; Store initializer value for char16
    store r1, [fp-64]
    ; Variable declaration
; Variable char17 allocated at [fp-68]
    mov r1, #10
    ; Store initializer value for char17
    store r1, [fp-68]
    ; Return statement
    mov r0, #0
    add sp, sp, #64
    pop fp
    ret 
log_sum_check_passed_n_6f9303c9_end:
    add sp, sp, #64
    pop fp
    ret 

    ; Function declaration
log_sum_check_failed_n_14bf5e22:
    push fp
    mov fp, sp
    sub sp, sp, #64
    ; Compound statement
    ; Variable declaration
; Variable char1 allocated at [fp-4]
    mov r1, #83
    ; Store initializer value for char1
    store r1, [fp-4]
    ; Variable declaration
; Variable char2 allocated at [fp-8]
    mov r1, #117
    ; Store initializer value for char2
    store r1, [fp-8]
    ; Variable declaration
; Variable char3 allocated at [fp-12]
    mov r1, #109
    ; Store initializer value for char3
    store r1, [fp-12]
    ; Variable declaration
; Variable char4 allocated at [fp-16]
    mov r1, #32
    ; Store initializer value for char4
    store r1, [fp-16]
    ; Variable declaration
; Variable char5 allocated at [fp-20]
    mov r1, #99
    ; Store initializer value for char5
    store r1, [fp-20]
    ; Variable declaration
; Variable char6 allocated at [fp-24]
    mov r1, #104
    ; Store initializer value for char6
    store r1, [fp-24]
    ; Variable declaration
; Variable char7 allocated at [fp-28]
    mov r1, #101
    ; Store initializer value for char7
    store r1, [fp-28]
    ; Variable declaration
; Variable char8 allocated at [fp-32]
    mov r1, #99
    ; Store initializer value for char8
    store r1, [fp-32]
    ; Variable declaration
; Variable char9 allocated at [fp-36]
    mov r1, #107
    ; Store initializer value for char9
    store r1, [fp-36]
    ; Variable declaration
; Variable char10 allocated at [fp-40]
    mov r1, #32
    ; Store initializer value for char10
    store r1, [fp-40]
    ; Variable declaration
; Variable char11 allocated at [fp-44]
    mov r1, #102
    ; Store initializer value for char11
    store r1, [fp-44]
    ; Variable declaration
; Variable char12 allocated at [fp-48]
    mov r1, #97
    ; Store initializer value for char12
    store r1, [fp-48]
    ; Variable declaration
; Variable char13 allocated at [fp-52]
    mov r1, #105
    ; Store initializer value for char13
    store r1, [fp-52]
    ; Variable declaration
; Variable char14 allocated at [fp-56]
    mov r1, #108
    ; Store initializer value for char14
    store r1, [fp-56]
    ; Variable declaration
; Variable char15 allocated at [fp-60]
    mov r1, #101
    ; Store initializer value for char15
    store r1, [fp-60]
    ; Variable declaration
; Variable char16 allocated at [fp-64]
    mov r1, #100
    ; Store initializer value for char16
    store r1, [fp-64]
    ; Variable declaration
; Variable char17 allocated at [fp-68]
    mov r1, #10
    ; Store initializer value for char17
    store r1, [fp-68]
    ; Return statement
    mov r0, #0
    add sp, sp, #64
    pop fp
    ret 
log_sum_check_failed_n_14bf5e22_end:
    add sp, sp, #64
    pop fp
    ret 

    ; Function declaration
set_log_length:
    push fp
    mov fp, sp
    sub sp, sp, #64
    ; Compound statement
    ; Variable declaration
; Variable length allocated at [fp-4]
    mov r1, #102
    ; Store initializer value for length
    store r1, [fp-4]
    ; Return statement
    mov r0, #0
    add sp, sp, #64
    pop fp
    ret 
set_log_length_end:
    add sp, sp, #64
    pop fp
    ret 

    ; Function declaration
main:
    push fp
    mov fp, sp
    sub sp, sp, #64
    ; Compound statement
    ; Function call
    call log_very_simple_string_d_f474b09e
    mov r0, r0
    ; Variable declaration
; Variable x allocated at [fp-4]
    mov r1, #10
    ; Store initializer value for x
    store r1, [fp-4]
    ; Function call
    call log_value_of_x_10_n_c529459d
    mov r0, r0
    ; Variable declaration
; Variable y allocated at [fp-8]
    mov r1, #20
    ; Store initializer value for y
    store r1, [fp-8]
    ; Function call
    call log_value_of_y_20_n_b62ac48a
    mov r0, r0
    ; Variable declaration
; Variable sum allocated at [fp-12]
    load r1, [fp-4]
    load r2, [fp-8]
    add r1, r1, r2
    ; Store initializer value for sum
    store r1, [fp-12]
    ; Function call
    call log_value_of_sum_30_n_0b323078
    mov r0, r0
    ; If statement
    load r1, [fp-12]
    mov r2, #3110
    cmp r1, r2
    seteq r0
    cmp r0, #0
    je L0
    ; Compound statement
    ; Function call
    call log_sum_check_passed_n_6f9303c9
    mov r0, r0
    ; Function call
    call set_log_length
    mov r0, r0
    ; Return statement
    mov r0, #133
    add sp, sp, #64
    pop fp
    ret 
    jmp L1
L0:
    ; Compound statement
    ; Function call
    call log_sum_check_failed_n_14bf5e22
    mov r0, r0
    ; Return statement
    mov r0, #444
    add sp, sp, #64
    pop fp
    ret 
L1:
main_end:
    add sp, sp, #64
    pop fp
    ret 


; Program entry point
_start:
    call main
    halt
