; Generated by Enhanced C Compiler
; Support for arrays, structs, malloc, and JVM features
.org 0x8000

; Initialize stack pointer
LOADI R30, #0x000F0000
; Initialize heap pointer
LOADI R29, #0x20000

; Function: main
main:
CALL printf
LOADI R1, #0
HALT
HALT


HALT
