; Generated by Simple C Compiler
; Custom RISC Assembly Output

    ; Runtime support functions
malloc:
    ; Simple malloc - returns fixed heap addresses
    load r1, heap_ptr
    add r2, r1, r0
    store r2, heap_ptr
    mov r0, r1
    ret

putchar:
    ; Output character in r0
    out r0
    ret

strlen:
    ; String length - string pointer in r0
    mov r1, r0
    mov r0, #0
strlen_loop:
    load r2, [r1]
    cmp r2, #0
    je strlen_end
    add r0, r0, #1
    add r1, r1, #1
    jmp strlen_loop
strlen_end:
    ret

; Data section
heap_ptr: .word 0x10000

    ; Compound statement
    ; Function declaration
write_display_reg:
    push fp
    mov fp, sp
    sub sp, sp, #64
    ; Compound statement
write_display_reg_end:
    add sp, sp, #64
    pop fp
    ret 

    ; Function declaration
put_text_char:
    push fp
    mov fp, sp
    sub sp, sp, #64
    ; Compound statement
    ; Variable declaration
; Variable pos allocated
    ; Undefined symbol
    mov r1, #0
    mov r2, #80
    mul r1, r1, r2
    ; Undefined symbol
    mov r2, #0
    add r1, r1, r2
    ; Store initializer value for pos
    ; Undefined symbol
    mov r1, #0
    mov r2, #8
    shl r1, r1, r2
    ; Undefined symbol
    mov r2, #0
    or r1, r1, r2
    ; Store to array element
    ; Undefined symbol
    mov r2, #0
    ; Undefined symbol
    mov r3, #0
    mul r3, r3, #4
    add r2, r2, r3
    store r1, [r2]
    mov r0, r1
put_text_char_end:
    add sp, sp, #64
    pop fp
    ret 

    ; Function declaration
put_pixel:
    push fp
    mov fp, sp
    sub sp, sp, #64
    ; Compound statement
    ; If statement
    ; Undefined symbol
    mov r1, #0
    mov r2, #0
    cmp r1, r2
    setge r1
    ; Undefined symbol
    mov r1, #0
    mov r2, #640
    cmp r1, r2
    setlt r2
    and r1, r1, r2
    ; Undefined symbol
    mov r1, #0
    mov r2, #0
    cmp r1, r2
    setge r2
    and r1, r1, r2
    ; Undefined symbol
    mov r1, #0
    mov r2, #480
    cmp r1, r2
    setlt r2
    and r0, r1, r2
    cmp r0, #0
    je L0
    ; Compound statement
    ; Undefined symbol
    mov r1, #0
    ; Store to array element
    ; Undefined symbol
    mov r2, #0
    ; Undefined symbol
    mov r1, #0
    mov r2, #640
    mul r1, r1, r2
    ; Undefined symbol
    mov r2, #0
    add r3, r1, r2
    mul r3, r3, #4
    add r2, r2, r3
    store r1, [r2]
    mov r0, r1
    jmp L1
L0:
L1:
put_pixel_end:
    add sp, sp, #64
    pop fp
    ret 

    ; Function declaration
main:
    push fp
    mov fp, sp
    sub sp, sp, #64
    ; Compound statement
    ; Variable declaration
; Variable i allocated
    ; Function call
    ; Undefined symbol
    mov r3, #0
    push r3
    mov r3, #0
    push r3
    call write_display_reg
    add sp, sp, #8
    mov r0, r0
    ; For loop (simplified)
    ; Compound statement
    ; Function call
    mov r3, #10
    push r3
    mov r3, #5
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #11
    push r3
    mov r3, #5
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #12
    push r3
    mov r3, #5
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #13
    push r3
    mov r3, #5
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #14
    push r3
    mov r3, #5
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #15
    push r3
    mov r3, #5
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #16
    push r3
    mov r3, #5
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #17
    push r3
    mov r3, #5
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #18
    push r3
    mov r3, #5
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #19
    push r3
    mov r3, #5
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #20
    push r3
    mov r3, #5
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #10
    push r3
    mov r3, #7
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #11
    push r3
    mov r3, #7
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #12
    push r3
    mov r3, #7
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #13
    push r3
    mov r3, #7
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #14
    push r3
    mov r3, #7
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #15
    push r3
    mov r3, #7
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #16
    push r3
    mov r3, #7
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #17
    push r3
    mov r3, #7
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #18
    push r3
    mov r3, #7
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #19
    push r3
    mov r3, #7
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #20
    push r3
    mov r3, #7
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #21
    push r3
    mov r3, #7
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; For loop (simplified)
    ; Compound statement
    ; Function call
    ; Undefined symbol
    mov r3, #0
    push r3
    mov r3, #1
    push r3
    call write_display_reg
    add sp, sp, #8
    mov r0, r0
    ; For loop (simplified)
    ; Compound statement
    ; Undefined symbol
    mov r1, #0
    ; Store to array element
    ; Undefined symbol
    mov r2, #0
    ; Undefined symbol
    mov r3, #0
    mul r3, r3, #4
    add r2, r2, r3
    store r1, [r2]
    mov r0, r1
    ; For loop (simplified)
    ; Compound statement
    ; For loop (simplified)
    ; Compound statement
    ; Function call
    ; Undefined symbol
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_pixel
    add sp, sp, #12
    mov r0, r0
    ; For loop (simplified)
    ; Compound statement
    ; For loop (simplified)
    ; Compound statement
    ; Function call
    ; Undefined symbol
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_pixel
    add sp, sp, #12
    mov r0, r0
    ; For loop (simplified)
    ; Compound statement
    ; Function call
    mov r1, #200
    ; Undefined symbol
    mov r2, #0
    add r3, r1, r2
    push r3
    mov r1, #200
    ; Undefined symbol
    mov r2, #0
    add r3, r1, r2
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_pixel
    add sp, sp, #12
    mov r0, r0
    ; Function call
    mov r1, #200
    ; Undefined symbol
    mov r2, #0
    add r3, r1, r2
    push r3
    mov r1, #400
    ; Undefined symbol
    mov r2, #0
    sub r3, r1, r2
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_pixel
    add sp, sp, #12
    mov r0, r0
    ; For loop (simplified)
    ; Compound statement
    ; Function call
    ; Undefined symbol
    mov r3, #0
    push r3
    mov r3, #2
    push r3
    call write_display_reg
    add sp, sp, #8
    mov r0, r0
    ; Function call
    mov r3, #5
    push r3
    mov r3, #20
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #6
    push r3
    mov r3, #20
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #7
    push r3
    mov r3, #20
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #8
    push r3
    mov r3, #20
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #9
    push r3
    mov r3, #20
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #10
    push r3
    mov r3, #20
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #11
    push r3
    mov r3, #20
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #12
    push r3
    mov r3, #20
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #13
    push r3
    mov r3, #20
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #14
    push r3
    mov r3, #20
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #5
    push r3
    mov r3, #22
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #6
    push r3
    mov r3, #22
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #7
    push r3
    mov r3, #22
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #8
    push r3
    mov r3, #22
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #9
    push r3
    mov r3, #22
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #10
    push r3
    mov r3, #22
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Function call
    mov r3, #11
    push r3
    mov r3, #22
    push r3
    mov r3, #0
    push r3
    ; Undefined symbol
    mov r3, #0
    push r3
    call put_text_char
    add sp, sp, #16
    mov r0, r0
    ; Return statement
    mov r0, #0
    add sp, sp, #64
    pop fp
    ret 
main_end:
    add sp, sp, #64
    pop fp
    ret 


; Program entry point
_start:
    call main
    halt
