; Generated by Simple C Compiler
; Custom RISC Assembly Output

.org 0x8000
_start:
    li sp, 0x000F0000
    call main
    li a0, 0
    halt

    ; Runtime support functions
malloc:
    ; Simple malloc - returns fixed heap addresses
    la t0, heap_ptr
    lw t1, 0(t0)
    add t2, t1, a0
    sw t2, 0(t0)
    mv a0, t1
    ret

putchar:
    ; Output character in a0
    li a7, 1
    ecall
    ret

strlen:
    ; String length - string pointer in a0
    mv t0, a0
    li a0, 0
strlen_loop:
    lb t1, 0(t0)
    beq t1, zero, strlen_end
    addi a0, a0, 1
    addi t0, t0, 1
    j strlen_loop
strlen_end:
    ret

; Data section
.align 4
heap_ptr: .word 0x10000

    ; Compound statement
    ; Function declaration
factorial:
    addi sp, sp, -16
    sw ra, 12(sp)
    sw s0, 8(sp)
    addi s0, sp, 16
    addi sp, sp, -256
    ; Parameter n at offset 0
    ; Compound statement
    ; If statement
    lw t0, 0(s0)
    li t1, 1
    slt t2, t1, t0
    xori a0, t2, 1
    beq a0, zero, L0
    ; Return statement
    li a0, 1
    addi sp, sp, 256
    lw s0, 8(sp)
    lw ra, 12(sp)
    addi sp, sp, 16
    ret 
    j L1
L0:
L1:
    ; Return statement
    lw t0, 0(s0)
    ; Function call
    lw t0, 0(s0)
    li t1, 1
    sub t2, t0, t1
    addi sp, sp, -4
    sw t2, 0(sp)
    call factorial
    addi sp, sp, 4
    mv t1, a0
    mul a0, t0, t1
    addi sp, sp, 256
    lw s0, 8(sp)
    lw ra, 12(sp)
    addi sp, sp, 16
    ret 
factorial_end:
    addi sp, sp, 256
    lw s0, 8(sp)
    lw ra, 12(sp)
    addi sp, sp, 16
    ret 

    ; Function declaration
main:
    addi sp, sp, -16
    sw ra, 12(sp)
    sw s0, 8(sp)
    addi s0, sp, 16
    addi sp, sp, -256
    ; Compound statement
    ; Variable declaration
    ; Initializing variable result at offset -12
    ; Function call
    li t2, 5
    addi sp, sp, -4
    sw t2, 0(sp)
    call factorial
    addi sp, sp, 4
    mv t0, a0
    sw t0, -12(s0)
    ; If statement
    lw t0, -12(s0)
    li t1, 120
    sub t2, t0, t1
    sltiu a0, t2, 1
    beq a0, zero, L2
    ; Compound statement
    ; Return statement
    li a0, 1
    addi sp, sp, 256
    lw s0, 8(sp)
    lw ra, 12(sp)
    addi sp, sp, 16
    ret 
    j L3
L2:
L3:
    ; Return statement
    li a0, 0
    addi sp, sp, 256
    lw s0, 8(sp)
    lw ra, 12(sp)
    addi sp, sp, 16
    ret 
main_end:
    addi sp, sp, 256
    lw s0, 8(sp)
    lw ra, 12(sp)
    addi sp, sp, 16
    ret 

