# Generated by Simple C Compiler
# Custom RISC Assembly Output

# Runtime support functions
malloc:
# Simple malloc - returns fixed heap addresses
load x1, heap_ptr
add x2, x1, x0
store x2, heap_ptr
mov x0, x1
ret

putchar:
# Output character in r0
li a7, 11
    ecall  # print char from x0
ret

strlen:
# String length - string pointer in r0
mov x1, x0
addi x0, zero, 0
strlen_loop:
lw x2, 0(x1)
#cmp x2, #0
je strlen_end
add x0, x0, #1
add x1, x1, #1
j strlen_loop
strlen_end:
ret

# Data section
heap_ptr: .word 0x10000

# Compound statement
# Function declaration
main:
addi sp, sp, -4
    sw fp, 0(sp)
mov fp, sp
sub sp, sp, #64
# Compound statement
# Variable declaration
# Variable a allocated at [fp-4]
addi x1, zero, 10
# Store initializer value for a
sw x1, 0(fp-4)
# Variable declaration
# Variable b allocated at [fp-8]
addi x1, zero, 3
# Store initializer value for b
sw x1, 0(fp-8)
# Variable declaration
# Variable result allocated at [fp-12]
lw x1, 0(fp-4)
lw x2, 0(fp-8)
add x1, x1, x2
# Store to variable result
sw x1, 0(fp-12)
mov x0, x1
lw x1, 0(fp-4)
lw x2, 0(fp-8)
sub x1, x1, x2
# Store to variable result
sw x1, 0(fp-12)
mov x0, x1
lw x1, 0(fp-4)
lw x2, 0(fp-8)
mul x1, x1, x2
# Store to variable result
sw x1, 0(fp-12)
mov x0, x1
lw x1, 0(fp-4)
lw x2, 0(fp-8)
div x1, x1, x2
# Store to variable result
sw x1, 0(fp-12)
mov x0, x1
lw x1, 0(fp-4)
lw x2, 0(fp-8)
mod x1, x1, x2
# Store to variable result
sw x1, 0(fp-12)
mov x0, x1
# Return statement
lw x0, 0(fp-12)
add sp, sp, #64
lw fp, 0(sp)
    addi sp, sp, 4
ret
main_end:
add sp, sp, #64
lw fp, 0(sp)
    addi sp, sp, 4
ret


# Program entry point
_start:
call main
ebreak
