# Generated by Simple C Compiler
# Custom RISC Assembly Output

# Runtime support functions
malloc:
# Simple malloc - returns fixed heap addresses
load x1, heap_ptr
add x2, x1, x0
store x2, heap_ptr
mov x0, x1
ret

putchar:
# Output character in r0
li a7, 11
    ecall  # print char from x0
ret

strlen:
# String length - string pointer in r0
mov x1, x0
addi x0, zero, 0
strlen_loop:
lw x2, 0(x1)
#cmp x2, #0
je strlen_end
add x0, x0, #1
add x1, x1, #1
j strlen_loop
strlen_end:
ret

# Data section
heap_ptr: .word 0x10000

# Compound statement

# Program entry point
_start:
call main
ebreak
