# Generated by Simple C Compiler
# Custom RISC Assembly Output

# Runtime support functions
malloc:
# Simple malloc - returns fixed heap addresses
load x1, heap_ptr
add x2, x1, x0
store x2, heap_ptr
mov x0, x1
ret

putchar:
# Output character in r0
li a7, 11
    ecall  # print char from x0
ret

strlen:
# String length - string pointer in r0
mov x1, x0
addi x0, zero, 0
strlen_loop:
lw x2, 0(x1)
#cmp x2, #0
je strlen_end
add x0, x0, #1
add x1, x1, #1
j strlen_loop
strlen_end:
ret

# Data section
heap_ptr: .word 0x10000

# Compound statement
# Function declaration
main:
addi sp, sp, -4
    sw fp, 0(sp)
mov fp, sp
sub sp, sp, #64
# Compound statement
# Variable declaration
# Variable result allocated at [fp-4]
addi x1, zero, 0
# Store initializer value for result
sw x1, 0(fp-4)
# Compound assignment - expanding to regular assignment
# Load current value of result
lw x2, 0(fp-4)
addi x3, zero, 10
add x1, x2, x3
# Store to variable result
sw x1, 0(fp-4)
mov x0, x1
# Compound assignment - expanding to regular assignment
# Load current value of result
lw x2, 0(fp-4)
addi x3, zero, 20
add x1, x2, x3
# Store to variable result
sw x1, 0(fp-4)
mov x0, x1
# Compound assignment - expanding to regular assignment
# Load current value of result
lw x2, 0(fp-4)
addi x3, zero, 30
add x1, x2, x3
# Store to variable result
sw x1, 0(fp-4)
mov x0, x1
# Compound assignment - expanding to regular assignment
# Load current value of result
lw x2, 0(fp-4)
addi x3, zero, 40
add x1, x2, x3
# Store to variable result
sw x1, 0(fp-4)
mov x0, x1
# Compound assignment - expanding to regular assignment
# Load current value of result
lw x2, 0(fp-4)
addi x3, zero, 50
add x1, x2, x3
# Store to variable result
sw x1, 0(fp-4)
mov x0, x1
# Function call
lea x3, str0
j str0_end
str0: .string "The sum is: %d
"
str0_end:
addi sp, sp, -4
    sw x3, 0(sp)
lw x3, 0(fp-4)
addi sp, sp, -4
    sw x3, 0(sp)
call printf
add sp, sp, #8
mov x0, x0
# Return statement
addi x0, zero, 0
add sp, sp, #64
lw fp, 0(sp)
    addi sp, sp, 4
ret
main_end:
add sp, sp, #64
lw fp, 0(sp)
    addi sp, sp, 4
ret


# Program entry point
_start:
call main
ebreak
