# Generated by Simple C Compiler
# Custom RISC Assembly Output

# Runtime support functions
malloc:
# Simple malloc - returns fixed heap addresses
load x1, heap_ptr
add x2, x1, x0
store x2, heap_ptr
mov x0, x1
ret

putchar:
# Output character in r0
li a7, 11
    ecall  # print char from x0
ret

strlen:
# String length - string pointer in r0
mov x1, x0
addi x0, zero, 0
strlen_loop:
lw x2, 0(x1)
#cmp x2, #0
je strlen_end
add x0, x0, #1
add x1, x1, #1
j strlen_loop
strlen_end:
ret

# Data section
heap_ptr: .word 0x10000

# Compound statement
# Function declaration
main:
addi sp, sp, -4
    sw fp, 0(sp)
mov fp, sp
sub sp, sp, #64
# Compound statement
# Function call
lea x3, str0
j str0_end
str0: .string "Very Simple String Demo
"
str0_end:
addi sp, sp, -4
    sw x3, 0(sp)
call log_string
add sp, sp, #4
mov x0, x0
# Variable declaration
# Variable x allocated at [fp-4]
addi x1, zero, 10
# Store initializer value for x
sw x1, 0(fp-4)
# Function call
lea x3, str1
j str1_end
str1: .string "Value of X=10
"
str1_end:
addi sp, sp, -4
    sw x3, 0(sp)
call log_string
add sp, sp, #4
mov x0, x0
# Variable declaration
# Variable y allocated at [fp-8]
addi x1, zero, 20
# Store initializer value for y
sw x1, 0(fp-8)
# Function call
lea x3, str2
j str2_end
str2: .string "Value of Y=20
"
str2_end:
addi sp, sp, -4
    sw x3, 0(sp)
call log_string
add sp, sp, #4
mov x0, x0
# Variable declaration
# Variable sum allocated at [fp-12]
lw x1, 0(fp-4)
lw x2, 0(fp-8)
add x1, x1, x2
# Store initializer value for sum
sw x1, 0(fp-12)
# Function call
lea x3, str3
j str3_end
str3: .string "Value of Sum=30
"
str3_end:
addi sp, sp, -4
    sw x3, 0(sp)
call log_string
add sp, sp, #4
mov x0, x0
# If statement
lw x1, 0(fp-12)
addi x2, zero, 3110
#cmp x1, x2
seteq x0
#cmp x0, #0
je L4
# Compound statement
# Function call
lea x3, str6
j str6_end
str6: .string "Sum check passed
"
str6_end:
addi sp, sp, -4
    sw x3, 0(sp)
call log_string
add sp, sp, #4
mov x0, x0
# Return statement
addi x0, zero, 133
add sp, sp, #64
lw fp, 0(sp)
    addi sp, sp, 4
ret
j L5
L4:
# Compound statement
# Function call
lea x3, str7
j str7_end
str7: .string "Sum check failed
"
str7_end:
addi sp, sp, -4
    sw x3, 0(sp)
call log_string
add sp, sp, #4
mov x0, x0
# Return statement
addi x0, zero, 444
add sp, sp, #64
lw fp, 0(sp)
    addi sp, sp, 4
ret
L5:
main_end:
add sp, sp, #64
lw fp, 0(sp)
    addi sp, sp, 4
ret


# Program entry point
_start:
call main
ebreak
