# Generated by Enhanced C Compiler
# Support for arrays, structs, malloc, and JVM features
.org 0x8000

# Initialize stack pointer
LOADI R30, #0x000F0000
# Initialize heap pointer
LOADI R29, #0x20000

# Function: main
main:
LOADI R2, #5
MOVE R1, R2
LOADI R3, #0
MOVE R1, R3
HALT
HALT


HALT
