; Generated by Enhanced C Compiler
; Support for arrays, structs, malloc, and JVM features
.org 0x8000

; Initialize stack pointer
LOADI R30, #0x000F0000
; Initialize heap pointer
LOADI R29, #0x20000

; Function: main
main:
LOADI R1, #str_0
; String literal: "\n=== Running test: %s ===\n"
LOADI R2, #str_1
; String literal: "test"
MOVE R2, R1
MOVE R3, R2
CALL printf
LOADI R3, #0
MOVE R1, R3
HALT
HALT


HALT
