; Generated by Enhanced C Compiler
; Support for arrays, structs, malloc, and JVM features
.org 0x8000

; Initialize stack pointer
LOADI R30, #0x000F0000
; Initialize heap pointer
LOADI R29, #0x20000

; Function: main
main:
LOADI R2, #0
MOVE R1, R2
LOADI R4, #0
MOVE R3, R4
LOADI R5, #17
MOVE R1, R5
LOADI R6, #5
MOVE R3, R6
MOD R7, R1, R3
MOVE R1, R7
LOADI R8, #3
MOVE R3, R8
ADD R9, R1, R3
MOVE R1, R9
HALT
HALT


HALT
