; Generated by Enhanced C Compiler
; Support for arrays, structs, malloc, and JVM features
.org 0x8000

; Initialize stack pointer
LOADI R30, #0x000F0000
; Initialize heap pointer
LOADI R29, #0x20000

; Function: main
main:
LOADI R1, #131072
LOADI R2, #0
LOADI R3, #42
LOADI R5, #4
MUL R4, R2, R5
ADD R4, R1, R4
STORE R3, R4, #0
LOADI R6, #0
LOADI R8, #4
MUL R7, R6, R8
ADD R7, R1, R7
LOAD R9, R7, #0
MOVE R1, R9
HALT
HALT


HALT
