# Generated by Simple C Compiler
# Custom RISC Assembly Output

.org 0x8000
_start:
li sp, 0x000F0000
call main
li a0, 0
ebreak

# Runtime support functions
malloc:
# Simple malloc - returns fixed heap addresses
la t0, heap_ptr
lw t1, 0(t0)
add t2, t1, a0
sw t2, 0(t0)
mv a0, t1
ret

putchar:
# Output character in a0
li a7, 1
ecall
ret

strlen:
# String length - string pointer in a0
mv t0, a0
li a0, 0
strlen_loop:
lb t1, 0(t0)
beq t1, zero, strlen_end
addi a0, a0, 1
addi t0, t0, 1
j strlen_loop
strlen_end:
ret

# Data section
.align 4
heap_ptr: .word 0x10000

# Compound statement
# Function declaration
main:
addi sp, sp, -16
sw ra, 12(sp)
sw s0, 8(sp)
addi s0, sp, 16
addi sp, sp, -256
# Compound statement
# Variable declaration
# Initializing variable principal at offset -12
li t0, 1000
sw t0, -12(s0)
# Variable declaration
# Initializing variable rate at offset -16
li t0, 5
sw t0, -16(s0)
# Variable declaration
# Initializing variable years at offset -20
li t0, 10
sw t0, -20(s0)
# Variable declaration
# Initializing variable amount at offset -24
lw t0, -12(s0)
sw t0, -24(s0)
# Variable declaration
# Initializing variable i at offset -28
li t0, 0
sw t0, -28(s0)
# While loop
L0:
lw t0, -28(s0)
lw t1, -20(s0)
slt a0, t0, t1
beq a0, zero, L1
# Compound statement
# Variable declaration
# Initializing variable interest at offset -32
lw t0, -24(s0)
lw t1, -16(s0)
mul t0, t0, t1
li t1, 100
div t0, t0, t1
sw t0, -32(s0)
lw t0, -24(s0)
lw t1, -32(s0)
add t0, t0, t1
sw t0, -24(s0)
mv a0, t0
lw t0, -28(s0)
mv a0, t0
addi t1, t0, 1
sw t1, -28(s0)
j L0
L1:
# If statement
lw t0, -24(s0)
li t1, 1500
slt a0, t1, t0
beq a0, zero, L2
# Compound statement
# If statement
lw t0, -24(s0)
li t1, 1700
slt a0, t0, t1
beq a0, zero, L4
# Compound statement
# Return statement
li a0, 1
addi sp, sp, 256
lw s0, 8(sp)
lw ra, 12(sp)
addi sp, sp, 16
ret
j L5
L4:
L5:
j L3
L2:
L3:
# Return statement
li a0, 0
addi sp, sp, 256
lw s0, 8(sp)
lw ra, 12(sp)
addi sp, sp, 16
ret
main_end:
addi sp, sp, 256
lw s0, 8(sp)
lw ra, 12(sp)
addi sp, sp, 16
ret

