; Generated by Simple C Compiler
; Custom RISC Assembly Output

.org 0x8000
_start:
    li sp, 0x000F0000
    call main
    li a0, 0
    halt

    ; Runtime support functions
malloc:
    ; Simple malloc - returns fixed heap addresses
    la t0, heap_ptr
    lw t1, 0(t0)
    add t2, t1, a0
    sw t2, 0(t0)
    mv a0, t1
    ret

putchar:
    ; Output character in a0
    li a7, 1
    ecall
    ret

strlen:
    ; String length - string pointer in a0
    mv t0, a0
    li a0, 0
strlen_loop:
    lb t1, 0(t0)
    beq t1, zero, strlen_end
    addi a0, a0, 1
    addi t0, t0, 1
    j strlen_loop
strlen_end:
    ret

; Data section
.align 4
heap_ptr: .word 0x10000

    ; Compound statement
    ; Function declaration
my_strlen:
    addi sp, sp, -16
    sw ra, 12(sp)
    sw s0, 8(sp)
    addi s0, sp, 16
    addi sp, sp, -256
    ; Parameter s at offset 0
    ; Compound statement
    ; Variable declaration
    ; Initializing variable len at offset -12
    li t0, 0
    sw t0, -12(s0)
    ; While loop
L0:
    lw t0, 0(s0)
    lb t0, 0(t0)
    li t1, 0
    sub t2, t0, t1
    sltu a0, zero, t2
    beq a0, zero, L1
    ; Compound statement
    lw t0, -12(s0)
    mv a0, t0
    addi t1, t0, 1
    sw t1, -12(s0)
    lw t0, 0(s0)
    mv a0, t0
    addi t1, t0, 1
    sw t1, 0(s0)
    j L0
L1:
    ; Return statement
    lw a0, -12(s0)
    addi sp, sp, 256
    lw s0, 8(sp)
    lw ra, 12(sp)
    addi sp, sp, 16
    ret 
my_strlen_end:
    addi sp, sp, 256
    lw s0, 8(sp)
    lw ra, 12(sp)
    addi sp, sp, 16
    ret 

    ; Function declaration
my_strcpy:
    addi sp, sp, -16
    sw ra, 12(sp)
    sw s0, 8(sp)
    addi s0, sp, 16
    addi sp, sp, -256
    ; Parameter dest at offset 4
    ; Parameter src at offset 0
    ; Compound statement
    ; While loop
L2:
    lw t0, 0(s0)
    lb t0, 0(t0)
    li t1, 0
    sub t2, t0, t1
    sltu a0, zero, t2
    beq a0, zero, L3
    ; Compound statement
    lw t0, 0(s0)
    lb t0, 0(t0)
    ; Store back to pointer dereference
    lw t4, 4(s0)
    sb t0, 0(t4)
    mv a0, t0
    lw t0, 4(s0)
    mv a0, t0
    addi t1, t0, 1
    sw t1, 4(s0)
    lw t0, 0(s0)
    mv a0, t0
    addi t1, t0, 1
    sw t1, 0(s0)
    j L2
L3:
    li t0, 0
    ; Store back to pointer dereference
    lw t4, 4(s0)
    sb t0, 0(t4)
    mv a0, t0
my_strcpy_end:
    addi sp, sp, 256
    lw s0, 8(sp)
    lw ra, 12(sp)
    addi sp, sp, 16
    ret 

    ; Function declaration
main:
    addi sp, sp, -16
    sw ra, 12(sp)
    sw s0, 8(sp)
    addi s0, sp, 16
    addi sp, sp, -256
    ; Compound statement
    ; Variable declaration
; Array str1[10] allocated (10 bytes)
    ; Variable declaration
; Array str2[10] allocated (10 bytes)
    li t0, 0
    ; Store back to array element
    addi t4, s0, -18
    li t5, 0
    add t4, t4, t5
    sb t0, 0(t4)
    mv a0, t0
    li t0, 0
    ; Store back to array element
    addi t4, s0, -18
    li t5, 1
    add t4, t4, t5
    sb t0, 0(t4)
    mv a0, t0
    li t0, 0
    ; Store back to array element
    addi t4, s0, -18
    li t5, 2
    add t4, t4, t5
    sb t0, 0(t4)
    mv a0, t0
    li t0, 0
    ; Store back to array element
    addi t4, s0, -18
    li t5, 3
    add t4, t4, t5
    sb t0, 0(t4)
    mv a0, t0
    li t0, 0
    ; Store back to array element
    addi t4, s0, -18
    li t5, 4
    add t4, t4, t5
    sb t0, 0(t4)
    mv a0, t0
    li t0, 0
    ; Store back to array element
    addi t4, s0, -18
    li t5, 5
    add t4, t4, t5
    sb t0, 0(t4)
    mv a0, t0
    ; Variable declaration
    ; Initializing variable len at offset -32
    ; Function call
    addi t2, s0, -18
    addi sp, sp, -4
    sw t2, 0(sp)
    call my_strlen
    addi sp, sp, 4
    mv t0, a0
    sw t0, -32(s0)
    ; If statement
    lw t0, -32(s0)
    li t1, 5
    sub t2, t0, t1
    sltu a0, zero, t2
    beq a0, zero, L4
    ; Return statement
    li a0, 0
    addi sp, sp, 256
    lw s0, 8(sp)
    lw ra, 12(sp)
    addi sp, sp, 16
    ret 
    j L5
L4:
L5:
    ; Function call
    addi t2, s0, -28
    addi sp, sp, -4
    sw t2, 0(sp)
    addi t2, s0, -18
    addi sp, sp, -4
    sw t2, 0(sp)
    call my_strcpy
    addi sp, sp, 8
    mv a0, a0
    ; If statement
    addi t0, s0, -28
    li t1, 0
    add t0, t0, t1
    lb t0, 0(t0)
    li t1, 0
    sub t2, t0, t1
    sltu a0, zero, t2
    beq a0, zero, L6
    ; Return statement
    li a0, 0
    addi sp, sp, 256
    lw s0, 8(sp)
    lw ra, 12(sp)
    addi sp, sp, 16
    ret 
    j L7
L6:
L7:
    ; If statement
    addi t0, s0, -28
    li t1, 4
    add t0, t0, t1
    lb t0, 0(t0)
    li t1, 0
    sub t2, t0, t1
    sltu a0, zero, t2
    beq a0, zero, L8
    ; Return statement
    li a0, 0
    addi sp, sp, 256
    lw s0, 8(sp)
    lw ra, 12(sp)
    addi sp, sp, 16
    ret 
    j L9
L8:
L9:
    ; If statement
    addi t0, s0, -28
    li t1, 5
    add t0, t0, t1
    lb t0, 0(t0)
    li t1, 0
    sub t2, t0, t1
    sltu a0, zero, t2
    beq a0, zero, L10
    ; Return statement
    li a0, 0
    addi sp, sp, 256
    lw s0, 8(sp)
    lw ra, 12(sp)
    addi sp, sp, 16
    ret 
    j L11
L10:
L11:
    ; Return statement
    li a0, 1
    addi sp, sp, 256
    lw s0, 8(sp)
    lw ra, 12(sp)
    addi sp, sp, 16
    ret 
main_end:
    addi sp, sp, 256
    lw s0, 8(sp)
    lw ra, 12(sp)
    addi sp, sp, 16
    ret 

